### ISSUE TITLE
wrong channel answer for bye command

### ISSUE THREAD

**Issue by ShiiFu** [SoulMourne/discordBot_Tyr#13]
When we use the command `bye`, the bot always answer in #general channel.

**Comment by TheGoodwin** [comment]
Added enhancement tag.
The bot should reply to the user shutting down the bot.

**Comment by TheGoodwin** [comment]
Add the indev label

**Comment by TheGoodwin** [comment]
Fixed on 418c04ee2a5cdd5680248d951523ebae75688ae9 commit
