### ISSUE TITLE
Ping give a double Pong

### ISSUE THREAD

**Issue by ShiiFu** [SoulMourne/discordBot_Tyr#14]
When we use `ping` command the bot pong us twice.

**Comment by TheGoodwin** [comment]
Added bug tag. Added the issue in the 0.1.0 milestone.
This issue happening on experimental branch will be corrected in the next release.

**Comment by TheGoodwin** [comment]
Add the experimental tag

**Comment by TheGoodwin** [comment]
Resolved on commit [b48f607](https://github.com/SoulMourne/discordBot_Tyr/commit/b48f607fe2f833d858bfe61ba9f96e331a986917)
